# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
language: ruby
rvm:
  - 2.7.2
jdk:
  - oraclejdk8
git:
  depth: 10
before_install:
- rvm install ruby-2.7.2
- rvm use 2.7.2
  - gem update bundler
