/* DO NOT EDIT: File is auto-generated by Resgen */
package iris.planner.resource;

@javax.annotation.Generated( "Resgen" )
public interface ResourceResources
  extends com.google.gwt.resources.client.ClientBundle
{
  ResourceResources INSTANCE = com.google.gwt.core.shared.GWT.create( ResourceResources.class );

  interface Style
    extends com.google.gwt.resources.client.CssResource
  {
    @ClassName( "glyphicon" )
    String glyphicon();
    @ClassName( "glyphicon-plus" )
    String glyphiconPlus();
  }

  @com.google.gwt.resources.client.DataResource.DoNotEmbed
  @com.google.gwt.resources.client.DataResource.MimeType( "application/font-woff" )
  @Source( "glyphiconsHalflingsRegular.woff" )
  com.google.gwt.resources.client.DataResource glyphiconsHalflingsRegular();

  @Source( "style.gss" )
  Style style();
}
