/* DO NOT EDIT: File is auto-generated by Resgen */
package iris.planner.resource;

@javax.annotation.Generated( "Resgen" )
public interface ResourceResources
  extends com.google.gwt.resources.client.ClientBundle
{
  ResourceResources INSTANCE = com.google.gwt.core.shared.GWT.create( ResourceResources.class );

  interface Style
    extends com.google.gwt.resources.client.CssResource
  {
    @ClassName( "incomplete" )
    String incomplete();
    @ClassName( "requirementNotMet" )
    String requirementNotMet();
  }

  @Source( "style.gss" )
  Style style();
}
